name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Check commit naming convention
              uses: wagoid/commitlint-github-action@v1
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
